version: '3'
services:
    # start just the db in the background
    # docker-compose up -d db
    db:
        image: postgres
        ports:
            - '5432:5432'
        env_file: .env
    # docker-compose build django
    # docker-compose run --rm django poetry run manage.py import 'data/*'
    # docker-compose run --rm -v /path/to/local/file.csv:/app/file.csv django poetry run manage.py [command] ./file.csv
    django:
        build: .
        command: poetry run celery -A jrdb worker -l info
        env_file: .env
        volumes:
            - .:/app
        depends_on:
            - db
            - redis
        ports:
            - '8000:8000'
    redis:
        image: redis
        ports:
            - '6379:6379'
