# Generated by Django 2.1.7 on 2019-03-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrdb', '0002_auto_20190326_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='contender_count',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='host_category',
            field=models.CharField(choices=[('KANTOU', '関東'), ('KANSAI', '関西'), ('LOCAL', 'ローカル')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='win5',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jockey',
            name='area',
            field=models.CharField(choices=[('KANTOU', '関東'), ('KANSAI', '関西'), ('OTHER', '他')], max_length=255, null=True),
        ),
    ]
