# Generated by Django 2.1.7 on 2019-03-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrdb', '0003_auto_20190326_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contender',
            name='weight_diff',
            field=models.SmallIntegerField(help_text='馬体重増減', null=True),
        ),
    ]
