# Generated by Django 2.1.7 on 2019-03-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrdb', '0004_auto_20190326_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contender',
            name='pace',
            field=models.SmallIntegerField(null=True),
        ),
    ]
