# Generated by Django 2.1.7 on 2019-03-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jrdb', '0005_auto_20190327_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contender',
            name='IDM',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contender',
            name='b3f_time',
            field=models.FloatField(help_text='前３Ｆタイム', null=True),
        ),
        migrations.AlterField(
            model_name='contender',
            name='f3f_time',
            field=models.FloatField(help_text='後３Ｆタイム', null=True),
        ),
        migrations.AlterField(
            model_name='contender',
            name='margin',
            field=models.FloatField(help_text='1(2)着タイム差', null=True),
        ),
        migrations.AlterField(
            model_name='contender',
            name='speed_index',
            field=models.SmallIntegerField(help_text='素点', null=True),
        ),
    ]
