# Generated by Django 2.1.7 on 2019-04-08 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jrdb', '0007_auto_20190330_0347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='pace_index',
            new_name='pace_idx',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='issued_bt_bracket_quinella',
            new_name='sold_bracket_quinella',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='issued_bt_duet',
            new_name='sold_duet',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='issued_bt_exacta',
            new_name='sold_exacta',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='issued_bt_quinella',
            new_name='sold_quinella',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='issued_bt_show',
            new_name='sold_show',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='issued_bt_trifecta',
            new_name='sold_trifecta',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='issued_bt_trio',
            new_name='sold_trio',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='issued_bt_win',
            new_name='sold_win',
        ),
    ]
