# Generated by Django 2.1.7 on 2019-04-10 14:04

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jrdb', '0008_auto_20190408_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='area',
            field=models.CharField(choices=[('KANTOU', '関東'), ('KANSAI', '関西'), ('OTHER', '他')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='cur_yr_flat_r',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), null=True, size=4),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='cur_yr_obst_r',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), null=True, size=4),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='prev_yr_flat_r',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), null=True, size=4),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='prev_yr_obst_r',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), null=True, size=4),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='sum_flat_r',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), null=True, size=4),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='sum_obst_r',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), null=True, size=4),
        ),
    ]
