# Generated by Django 2.1.7 on 2019-04-13 02:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jrdb', '0010_auto_20190411_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='odds_trio',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=816),
        ),
        migrations.AddField(
            model_name='race',
            name='odds_exacta',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=306),
        ),
        migrations.AddField(
            model_name='race',
            name='odds_trifecta',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=4896),
        ),
        migrations.AddField(
            model_name='race',
            name='odds_duet',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=153),
        ),
        migrations.AddField(
            model_name='race',
            name='odds_win',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=18),
        ),
        migrations.AddField(
            model_name='race',
            name='odds_show',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=18),
        ),
        migrations.AddField(
            model_name='race',
            name='odds_quinella',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(null=True), null=True, size=153),
        ),
    ]
