# Generated by Django 2.1.7 on 2019-04-14 02:47

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jrdb', '0011_auto_20190413_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='dam_birth_yr',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='horse',
            name='damsire_birth_yr',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='horse',
            name='is_retired',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='horse',
            name='sire_birth_yr',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='bs_track_bias',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), null=True, size=3, verbose_name='Backstretch track bias'),
        ),
        migrations.AlterField(
            model_name='race',
            name='c1_track_bias',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), null=True, size=3),
        ),
        migrations.AlterField(
            model_name='race',
            name='c2_track_bias',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), null=True, size=3),
        ),
        migrations.AlterField(
            model_name='race',
            name='c3_track_bias',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), null=True, size=3),
        ),
        migrations.AlterField(
            model_name='race',
            name='c4_track_bias',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), null=True, size=5),
        ),
        migrations.AlterField(
            model_name='race',
            name='hs_track_bias',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), null=True, size=5, verbose_name='Homestretch track bias'),
        ),
    ]
