from django.db import models

from jrdb.models import BaseModel, choices


class Contender(BaseModel):
    race = models.ForeignKey('jrdb.Race', on_delete=models.CASCADE, verbose_name='レース')
    horse = models.ForeignKey('jrdb.Horse', on_delete=models.CASCADE, verbose_name='馬')
    jockey = models.ForeignKey('jrdb.Jockey', on_delete=models.CASCADE, verbose_name='騎手')
    trainer = models.ForeignKey('jrdb.Trainer', on_delete=models.CASCADE, verbose_name='調教師')
    num = models.PositiveSmallIntegerField(verbose_name='馬番')

    # SEDから取得（成績系）
    order_of_finish = models.PositiveSmallIntegerField(verbose_name='着順')
    penalty = models.CharField(verbose_name='異常区分', max_length=255, choices=choices.PENALTY.CHOICES())
    time = models.FloatField(verbose_name='タイム', null=True)
    mounted_weight = models.FloatField(verbose_name='斤量')
    odds_win = models.FloatField(verbose_name='確定単勝オッズ', null=True)
    odds_show = models.FloatField(verbose_name='確定複勝オッズ下', null=True)
    odds_win_10AM = models.FloatField(verbose_name='10時単勝オッズ', null=True)
    odds_show_10AM = models.FloatField(verbose_name='10時複勝オッズ', null=True)
    popularity = models.PositiveSmallIntegerField(verbose_name='確定単勝人気順位')

    IDM = models.SmallIntegerField(verbose_name='ＩＤＭ', null=True)
    speed_idx = models.SmallIntegerField(verbose_name='素点', null=True)
    pace = models.SmallIntegerField(verbose_name='ペース', null=True)
    positioning = models.SmallIntegerField(verbose_name='位置取', null=True)
    late_start = models.PositiveSmallIntegerField(verbose_name='出遅', null=True)
    disadvt = models.PositiveSmallIntegerField(verbose_name='不利', null=True)
    b3f_disadvt = models.PositiveSmallIntegerField(verbose_name='前不利', null=True, help_text='前３Ｆ内での不利')
    mid_disadvt = models.PositiveSmallIntegerField(verbose_name='中不利', null=True, help_text='道中での不利')
    f3f_disadvt = models.PositiveSmallIntegerField(verbose_name='後不利', null=True, help_text='後３Ｆ内での不利')

    race_line = models.CharField(verbose_name='コース取り', max_length=255, choices=choices.RACE_LINE.CHOICES())
    improvement = models.CharField(verbose_name='上昇度コード', max_length=255, choices=choices.IMPROVEMENT.CHOICES())
    physique = models.CharField(verbose_name='馬体コード', max_length=255, choices=choices.PHYSIQUE.CHOICES())
    demeanor = models.CharField(verbose_name='気配コード', max_length=255, choices=choices.DEMEANOR.CHOICES())

    pace_cat = models.CharField(verbose_name='馬ペース', max_length=255, choices=choices.PACE_CATEGORY.CHOICES())
    b3f_time_idx = models.FloatField(verbose_name='テン指数', null=True, help_text='前３Ｆタイムを指数化したもの')
    f3f_time_idx = models.FloatField(verbose_name='上がり指数', null=True, help_text='後３Ｆタイムを指数化したもの')
    pace_idx = models.FloatField(verbose_name='ペース指数', null=True, help_text='馬のペースを指数化したもの')
    margin = models.FloatField(verbose_name='1(2)着タイム差', null=True, help_text='0.1秒単位')
    b3f_time = models.FloatField(verbose_name='前３Ｆタイム', null=True, help_text='0.1秒単位')
    f3f_time = models.FloatField(verbose_name='後３Ｆタイム', null=True, help_text='0.1秒単位')

    c1p = models.PositiveSmallIntegerField(verbose_name='コーナー順位１', null=True)
    c2p = models.PositiveSmallIntegerField(verbose_name='コーナー順位２', null=True)
    c3p = models.PositiveSmallIntegerField(verbose_name='コーナー順位３', null=True)
    c4p = models.PositiveSmallIntegerField(verbose_name='コーナー順位４', null=True)

    b3f_1p_margin = models.FloatField(verbose_name='前３Ｆ先頭差', null=True, help_text='前３Ｆ地点での先頭とのタイム差（0.1秒単位）')
    f3f_1p_margin = models.FloatField(verbose_name='後３Ｆ先頭差', null=True, help_text='後３Ｆ地点での先頭とのタイム差（0.1秒単位）')

    weight = models.PositiveSmallIntegerField(verbose_name='馬体重')
    weight_diff = models.SmallIntegerField(verbose_name='馬体重増減', null=True)

    run_style = models.CharField(verbose_name='レース脚質', max_length=255, choices=choices.RUNNING_STYLE.CHOICES())
    purse = models.FloatField()
    pace_flow = models.ForeignKey('jrdb.PaceFlowCode', on_delete=models.CASCADE, verbose_name='本賞金', null=True)
    c4_race_line = models.CharField(verbose_name='４角コース取り', max_length=255, choices=choices.RACE_LINE.CHOICES(), help_text='1:最内,2:内,3:中,4:外,5:大外')

    # KYIから取得（前日系）
    prel_jockey_idx = models.FloatField(verbose_name='騎手指数', help_text='基準オッズと騎手の連対率の関係を基に算出された指数値')
    prel_info_idx = models.FloatField(verbose_name='情報指数', help_text='基準オッズ、厩舎指数、調教指数等様々な情報を基に算出された指数値')
    prel_total_idx = models.FloatField(verbose_name='総合指数', help_text='ＩＤＭ、騎手指数、情報指数を合計した値')
    prel_pop_idx = models.PositiveSmallIntegerField(verbose_name='人気指数', null=True, help_text='その馬の人気を指数化した値')
    prel_trainer_idx = models.FloatField(verbose_name='調教指数')
    prel_stable_idx = models.FloatField(verbose_name='厩舎指数')
    flat_out_run_idx = models.SmallIntegerField(verbose_name='激走指数')
    rotation = models.PositiveSmallIntegerField(verbose_name='ローテーション', null=True, help_text='間に金曜日が入っている数で決定、連闘は０、初出走はNULL')
    prel_IDM = models.FloatField(verbose_name='前日ＩＤＭ', null=True)
    prel_run_style = models.CharField(verbose_name='前日脚質', max_length=255, choices=choices.RUNNING_STYLE.CHOICES())
    dist_apt = models.PositiveSmallIntegerField(verbose_name='距離適性')
    prel_improvement = models.CharField(verbose_name='前日上昇度コード', max_length=255, choices=choices.IMPROVEMENT.CHOICES())
    odds_win_base = models.FloatField(verbose_name='基準オッズ')
    pop_win_base = models.PositiveSmallIntegerField(verbose_name='基準人気順位')
    odds_show_base = models.FloatField(verbose_name='基準複勝オッズ')
    pop_show_base = models.PositiveSmallIntegerField(verbose_name='基準複勝人気順位')
    sym_sp_c_dbl = models.PositiveSmallIntegerField(verbose_name='特定情報◎')
    sym_sp_c = models.PositiveSmallIntegerField(verbose_name='特定情報○')
    sym_sp_t_dark = models.PositiveSmallIntegerField(verbose_name='特定情報▲')
    sym_sp_t = models.PositiveSmallIntegerField(verbose_name='特定情報△')
    sym_sp_x = models.PositiveSmallIntegerField(verbose_name='特定情報×')
    sym_total_c_dbl = models.PositiveSmallIntegerField(verbose_name='総合情報◎')
    sym_total_c = models.PositiveSmallIntegerField(verbose_name='総合情報○')
    sym_total_t_dark = models.PositiveSmallIntegerField(verbose_name='総合情報▲')
    sym_total_t = models.PositiveSmallIntegerField(verbose_name='総合情報△')
    sym_total_x = models.PositiveSmallIntegerField(verbose_name='総合情報×')
    trainer_outlook = models.CharField(verbose_name='調教矢印コード', max_length=255, choices=choices.TRAINER_HORSE_EVALUATION.CHOICES())
    stable_outlook = models.CharField(verbose_name='厩舎評価コード', max_length=255, choices=choices.STABLE_HORSE_EVALUATION.CHOICES())
    jockey_exp_1o2_place_rate = models.FloatField(verbose_name='騎手期待連対率', help_text='騎手Ａが単勝基準オッズＢの馬に乗った場合の過去の成績を集計し、算出された連対率')
    paddock_observed_hoof = models.CharField(verbose_name='蹄コード', max_length=255, choices=choices.PADDOCK_OBSERVED_HOOF.CHOICES())
    yield_track_apt = models.CharField(verbose_name='重適正コード', max_length=255, choices=choices.YIELDING_TRACK_APTITUDE.CHOICES())
    blinker = models.CharField(verbose_name='ブリンカー', max_length=255, choices=choices.BLINKER.CHOICES())
    post_position = models.PositiveSmallIntegerField(verbose_name='枠番')

    # 展開予想データ
    prel_b3f_time_idx = models.FloatField(verbose_name='予想テン指数', null=True)
    prel_pace_idx = models.FloatField(verbose_name='予想ペース指数', null=True)
    prel_f3f_time_idx = models.FloatField(verbose_name='予想上がり指数', null=True)
    prel_position_idx = models.FloatField(verbose_name='予想位置指数', null=True)
    prel_pace_cat = models.CharField(verbose_name='馬ペース', max_length=255, null=True, choices=choices.PACE_CATEGORY.CHOICES())
    mid_race_position = models.PositiveSmallIntegerField(verbose_name='道中順位', null=True)
    mid_race_margin = models.FloatField(verbose_name='道中差')
    mid_race_line = models.CharField(verbose_name='道中内外', max_length=255, null=True, choices=choices.RACE_LINE.CHOICES())
    f3f_position = models.PositiveSmallIntegerField(verbose_name='後３Ｆ順位')
    f3f_margin = models.FloatField(verbose_name='後３Ｆ差')
    f3f_race_line = models.CharField(verbose_name='後３Ｆ内外', max_length=255, null=True, choices=choices.RACE_LINE.CHOICES())
    goal_position = models.PositiveSmallIntegerField(verbose_name='ゴール順位', null=True)
    goal_margin = models.FloatField(verbose_name='ゴール差', null=True)
    goal_race_line = models.CharField(verbose_name='ゴール内外', max_length=255, null=True, choices=choices.RACE_LINE.CHOICES())
    race_development_symbol = models.CharField(verbose_name='展開記号', max_length=255, null=True, choices=choices.RACE_DEVELOPMENT_SYMBOL.CHOICES())

    dist_apt_2 = models.PositiveSmallIntegerField(verbose_name='距離適性２')
    # null is not a valid value for is_cancelled, so do not use NullBooleanField
    # but may be missing during import, so setting null=True on BooleanField
    is_cancelled = models.BooleanField(verbose_name='取消フラグ', null=True, default=False)
    flat_out_run_position = models.PositiveSmallIntegerField(verbose_name='激走順位', null=True, help_text='レース出走馬中での順位')
    LS_idx_position = models.PositiveSmallIntegerField(verbose_name='LS指数順位', null=True)
    b3f_idx_position = models.PositiveSmallIntegerField(verbose_name='テン指数順位', null=True)
    pace_idx_position = models.PositiveSmallIntegerField(verbose_name='ペース指数順位', null=True)
    f3f_idx_position = models.PositiveSmallIntegerField(verbose_name='上がり指数順位', null=True)
    positioning_idx_position = models.PositiveSmallIntegerField(verbose_name='位置指数順位', null=True)
    jockey_exp_win_rate = models.FloatField(verbose_name='騎手期待単勝率', null=True)
    jockey_exp_show_rate = models.FloatField(verbose_name='騎手期待３着内率', null=True)
    transport_category = models.CharField(verbose_name='輸送区分', max_length=255, null=True, choices=choices.TRANSPORT_CATEGORY.CHOICES())

    figure = models.CharField(max_length=255)
    figure_overall_1 = models.CharField(max_length=255)
    figure_overall_2 = models.CharField(max_length=255)
    figure_overall_3 = models.CharField(max_length=255)
    horse_sp_mention_1 = models.CharField(max_length=255)
    horse_sp_mention_2 = models.CharField(max_length=255)
    horse_sp_mention_3 = models.CharField(max_length=255)
    horse_start_idx = models.CharField(max_length=255)
    late_start_rate = models.CharField(max_length=255)
    big_bet_idx = models.CharField(max_length=255)
    big_bet_symbol = models.CharField(max_length=255)
    rank_lowered = models.CharField(max_length=255)
    flat_out_run_type = models.CharField(max_length=255)
    rest_reason_code = models.CharField(max_length=255)
    nth_race_since_training_start = models.CharField(max_length=255)
    training_start_date = models.CharField(max_length=255)
    nth_day_since_training_start = models.CharField(max_length=255)
    pasture_name = models.CharField(max_length=255)
    pasture_rank = models.CharField(max_length=255)
    stable_rank = models.CharField(max_length=255)

    class Meta:
        db_table = 'contenders'
        unique_together = ('race', 'horse', 'jockey', 'trainer')
